### ISSUE TITLE
Make the dependencies optional

### ISSUE THREAD

**Issue by seagle0128** [xuchunyang/youdao-dictionary.el#37]
Since `posframe` is supported but optional now, can we make `popup` and `pos-tip` optional as well?

BTW, `org-mode` is applied in the buffer, so it also can be applied in `posframe`. Please refer to https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-utils.el#L52

**Comment by xuchunyang** [comment]
posframe is optional because it requires much newer version of Emacs than youdao-dictionary itself. It's not a good idea to make popup/pos-tip optional now since they are already required for a long time.

I am not familiar with posframe. If you like that feature, you can implement it and submit a PR.

**Comment by seagle0128** [comment]
Also refer to https://github.com/tumashu/posframe/issues/52.
