### ISSUE TITLE
popup-tip is void func

### ISSUE THREAD

**Issue by zilongshanren** [xuchunyang/youdao-dictionary.el#6]

**Comment by xuchunyang** [comment]
How did you install `youdao-dictionary`? is `popup` now available? (or can <kbd>M-x find-library</kbd> find it?)

`popup-tip` is a function defined in the `popup` package (one of dependencies of `youdao-dictionary`), if you install `youdao-dictionary` via package.el, you should have all dependencies installed, otherwise, you have install them yourself.

**Comment by zilongshanren** [comment]
@xuchunyang 
I could find the `popup-tip` library but the compiled byte code is wrong.
I recompile it and the issue was resolved.
Thanks.
